name = "Spectacular Shatter Buddies"
love_version = "0.10.2"
default_targets = ["win32", "appimage"]
build_directory = "builds"
icon_file = "untracked/icon.png"

love_files = [
	"::git-ls-tree::",
	"-*/.*", # hidden files
	"-./tools/*", "-./other/*", "-./characters/#myrtle/*",
	"-*.blend",	"-*.bat",
	"-./README.md",
	"./builddata.lua",
]

[archive_files]
"untracked/deps/libraries.txt" = "libraries.txt"
"untracked/deps/licenses" = "licenses"
"untracked/.itch.toml" = ".itch.toml"

[hooks]
prebuild = [
	"generate_changelog.py", # generate from git history
	"generate_builddata.py", # generates .lua file with commit, date, etc.
]
postbuild = [
	"butler_push.py", # upload to itch
	"update_current_version.py", # update current version info on lobby server
]

[windows]
[windows.exe_metadata]
LegalCopyright = "Copyright 2019 Joel Schumacher"

[win32]
shared_libraries = [
	"tools/enet2/enet2.dll",
	"tools/libcurl.dll",
]

[appimage]
shared_libraries = [
	"tools/enet2/enet2.so",
	"/lib/x86_64-linux-gnu/libcurl.so",
]

# OSX??

